import { sql } from "drizzle-orm";

import type { Database } from "../client.js";
import { skills } from "../schema/tables.js";

export interface SkillSeedEntry {
  name: string;
  label: string;
  aliases: string[];
}

/** Canonical developer skills for JobFinder skill matching and extraction. */
export const SKILL_SEED_ENTRIES: SkillSeedEntry[] = [
  // ── Languages ──────────────────────────────────────────────────────────────
  { name: "typescript", label: "TypeScript", aliases: ["ts", "type script"] },
  { name: "javascript", label: "JavaScript", aliases: ["js", "ecmascript", "es6", "es2015"] },
  { name: "python", label: "Python", aliases: ["py", "python3"] },
  { name: "rust", label: "Rust", aliases: ["rustlang"] },
  { name: "go", label: "Go", aliases: ["golang"] },
  { name: "java", label: "Java", aliases: ["openjdk", "jdk"] },
  { name: "kotlin", label: "Kotlin", aliases: [] },
  { name: "scala", label: "Scala", aliases: [] },
  { name: "csharp", label: "C#", aliases: ["c#", "dotnet-c#", "c sharp"] },
  { name: "fsharp", label: "F#", aliases: ["f#"] },
  { name: "vbnet", label: "VB.NET", aliases: ["vb.net", "visual basic .net"] },
  { name: "ruby", label: "Ruby", aliases: ["rb"] },
  { name: "php", label: "PHP", aliases: [] },
  { name: "swift", label: "Swift", aliases: [] },
  { name: "objective-c", label: "Objective-C", aliases: ["objc", "obj-c"] },
  { name: "c", label: "C", aliases: [] },
  { name: "cpp", label: "C++", aliases: ["c++", "cplusplus"] },
  { name: "r", label: "R", aliases: ["r-lang", "r language"] },
  { name: "matlab", label: "MATLAB", aliases: [] },
  { name: "perl", label: "Perl", aliases: [] },
  { name: "lua", label: "Lua", aliases: [] },
  { name: "haskell", label: "Haskell", aliases: [] },
  { name: "elixir", label: "Elixir", aliases: [] },
  { name: "erlang", label: "Erlang", aliases: [] },
  { name: "clojure", label: "Clojure", aliases: [] },
  { name: "dart", label: "Dart", aliases: [] },
  { name: "groovy", label: "Groovy", aliases: [] },
  { name: "bash", label: "Bash", aliases: ["shell", "sh", "bourne shell"] },
  { name: "powershell", label: "PowerShell", aliases: ["pwsh"] },
  { name: "sql", label: "SQL", aliases: ["structured query language"] },
  { name: "html", label: "HTML", aliases: ["html5"] },
  { name: "css", label: "CSS", aliases: ["css3"] },
  { name: "solidity", label: "Solidity", aliases: [] },
  { name: "zig", label: "Zig", aliases: [] },
  { name: "wasm", label: "WebAssembly", aliases: ["webassembly", "wasm"] },

  // ── Frontend ───────────────────────────────────────────────────────────────
  { name: "react", label: "React", aliases: ["reactjs", "react.js"] },
  { name: "vue", label: "Vue.js", aliases: ["vuejs", "vue.js", "vue 3"] },
  { name: "angular", label: "Angular", aliases: ["angularjs", "angular 2+"] },
  { name: "svelte", label: "Svelte", aliases: ["sveltekit"] },
  { name: "nextjs", label: "Next.js", aliases: ["next.js", "next"] },
  { name: "nuxt", label: "Nuxt", aliases: ["nuxtjs", "nuxt.js"] },
  { name: "remix", label: "Remix", aliases: ["remix.run"] },
  { name: "astro", label: "Astro", aliases: [] },
  { name: "solidjs", label: "SolidJS", aliases: ["solid", "solid.js"] },
  { name: "qwik", label: "Qwik", aliases: [] },
  { name: "ember", label: "Ember.js", aliases: ["emberjs", "ember.js"] },
  { name: "jquery", label: "jQuery", aliases: [] },
  { name: "tailwindcss", label: "Tailwind CSS", aliases: ["tailwind", "tailwind css"] },
  { name: "bootstrap", label: "Bootstrap", aliases: [] },
  { name: "sass", label: "Sass", aliases: ["scss"] },
  { name: "less", label: "Less", aliases: [] },
  { name: "styled-components", label: "styled-components", aliases: ["styled components"] },
  { name: "redux", label: "Redux", aliases: ["redux toolkit", "rtk"] },
  { name: "zustand", label: "Zustand", aliases: [] },
  { name: "mobx", label: "MobX", aliases: [] },
  { name: "tanstack-query", label: "TanStack Query", aliases: ["react-query", "tanstack query"] },
  { name: "react-router", label: "React Router", aliases: [] },
  { name: "vite", label: "Vite", aliases: [] },
  { name: "webpack", label: "Webpack", aliases: [] },
  { name: "rollup", label: "Rollup", aliases: ["rollup.js"] },
  { name: "esbuild", label: "esbuild", aliases: [] },
  { name: "storybook", label: "Storybook", aliases: [] },
  { name: "material-ui", label: "Material UI", aliases: ["mui", "material ui"] },
  { name: "chakra-ui", label: "Chakra UI", aliases: ["chakra"] },
  { name: "ant-design", label: "Ant Design", aliases: ["antd"] },
  { name: "radix-ui", label: "Radix UI", aliases: ["radix"] },
  { name: "threejs", label: "Three.js", aliases: ["three.js", "three"] },
  { name: "d3", label: "D3.js", aliases: ["d3.js", "d3"] },
  { name: "pwa", label: "Progressive Web Apps", aliases: ["pwa", "progressive web app"] },

  // ── Backend & runtime ──────────────────────────────────────────────────────
  { name: "nodejs", label: "Node.js", aliases: ["node.js", "node"] },
  { name: "deno", label: "Deno", aliases: [] },
  { name: "bun", label: "Bun", aliases: [] },
  { name: "express", label: "Express", aliases: ["express.js", "expressjs"] },
  { name: "fastify", label: "Fastify", aliases: [] },
  { name: "nestjs", label: "NestJS", aliases: ["nest.js", "nest"] },
  { name: "koa", label: "Koa", aliases: ["koa.js"] },
  { name: "hapi", label: "hapi", aliases: ["hapi.js"] },
  { name: "django", label: "Django", aliases: [] },
  { name: "flask", label: "Flask", aliases: [] },
  { name: "fastapi", label: "FastAPI", aliases: [] },
  { name: "spring", label: "Spring", aliases: ["spring framework"] },
  { name: "spring-boot", label: "Spring Boot", aliases: ["springboot"] },
  {
    name: "jakarta-ee",
    label: "Jakarta EE",
    aliases: ["java ee", "j2ee", "jee", "jakarta ee", "enterprise java"],
  },
  { name: "quarkus", label: "Quarkus", aliases: [] },
  { name: "micronaut", label: "Micronaut", aliases: [] },
  { name: "aspnet-core", label: "ASP.NET Core", aliases: ["asp.net core", "aspnetcore"] },
  { name: "rails", label: "Ruby on Rails", aliases: ["ruby on rails", "ror"] },
  { name: "laravel", label: "Laravel", aliases: [] },
  { name: "symfony", label: "Symfony", aliases: [] },
  { name: "phoenix", label: "Phoenix", aliases: ["phoenix framework"] },
  { name: "actix", label: "Actix", aliases: ["actix-web", "actix web"] },
  { name: "rocket", label: "Rocket", aliases: ["rocket.rs"] },
  { name: "gin", label: "Gin", aliases: ["gin-gonic"] },
  { name: "echo", label: "Echo", aliases: ["echo framework", "labstack echo"] },
  { name: "fiber", label: "Fiber", aliases: ["gofiber", "go fiber"] },
  { name: "dotnet", label: ".NET", aliases: [".net", "dotnet core", ".net core"] },
  { name: "play-framework", label: "Play Framework", aliases: ["play", "play framework"] },
  { name: "strapi", label: "Strapi", aliases: [] },
  { name: "graphql", label: "GraphQL", aliases: ["gql"] },
  { name: "apollo-graphql", label: "Apollo GraphQL", aliases: ["apollo", "apollo server"] },
  { name: "trpc", label: "tRPC", aliases: [] },
  { name: "grpc", label: "gRPC", aliases: [] },
  { name: "rest", label: "REST", aliases: ["rest api", "restful", "restful api"] },
  { name: "openapi", label: "OpenAPI", aliases: ["open api", "swagger spec"] },
  { name: "swagger", label: "Swagger", aliases: [] },
  { name: "websocket", label: "WebSocket", aliases: ["websockets", "ws"] },

  // ── Mobile ─────────────────────────────────────────────────────────────────
  { name: "react-native", label: "React Native", aliases: ["reactnative"] },
  { name: "flutter", label: "Flutter", aliases: [] },
  { name: "swiftui", label: "SwiftUI", aliases: ["swift ui"] },
  { name: "jetpack-compose", label: "Jetpack Compose", aliases: ["compose", "jetpack compose"] },
  { name: "xamarin", label: "Xamarin", aliases: [] },
  { name: "ionic", label: "Ionic", aliases: [] },
  { name: "capacitor", label: "Capacitor", aliases: [] },
  { name: "expo", label: "Expo", aliases: [] },
  { name: "android", label: "Android", aliases: ["android development", "android sdk"] },
  { name: "ios", label: "iOS", aliases: ["ios development", "iphone development"] },
  {
    name: "kotlin-multiplatform",
    label: "Kotlin Multiplatform",
    aliases: ["kmp", "kotlin multiplatform mobile"],
  },
  { name: "maui", label: ".NET MAUI", aliases: ["maui", ".net maui"] },

  // ── Databases ──────────────────────────────────────────────────────────────
  { name: "postgresql", label: "PostgreSQL", aliases: ["postgres", "psql", "pg"] },
  { name: "mysql", label: "MySQL", aliases: [] },
  { name: "mariadb", label: "MariaDB", aliases: [] },
  { name: "sqlite", label: "SQLite", aliases: [] },
  { name: "mongodb", label: "MongoDB", aliases: ["mongo"] },
  { name: "redis", label: "Redis", aliases: [] },
  { name: "elasticsearch", label: "Elasticsearch", aliases: ["elastic search", "es"] },
  { name: "dynamodb", label: "DynamoDB", aliases: ["aws dynamodb", "amazon dynamodb"] },
  { name: "cassandra", label: "Cassandra", aliases: ["apache cassandra"] },
  { name: "cockroachdb", label: "CockroachDB", aliases: ["cockroach"] },
  { name: "neo4j", label: "Neo4j", aliases: [] },
  { name: "influxdb", label: "InfluxDB", aliases: [] },
  { name: "timescaledb", label: "TimescaleDB", aliases: ["timescale"] },
  { name: "couchdb", label: "CouchDB", aliases: [] },
  {
    name: "oracle",
    label: "Oracle Database",
    aliases: ["oracle db", "oracle database", "oracle sql"],
  },
  { name: "sql-server", label: "SQL Server", aliases: ["mssql", "microsoft sql server", "ms sql"] },
  { name: "firestore", label: "Firestore", aliases: ["cloud firestore", "google firestore"] },
  { name: "cosmosdb", label: "Cosmos DB", aliases: ["azure cosmos db", "cosmos db"] },
  { name: "snowflake", label: "Snowflake", aliases: [] },
  { name: "bigquery", label: "BigQuery", aliases: ["google bigquery", "gcp bigquery"] },
  { name: "redshift", label: "Redshift", aliases: ["aws redshift", "amazon redshift"] },
  { name: "clickhouse", label: "ClickHouse", aliases: [] },
  { name: "duckdb", label: "DuckDB", aliases: [] },
  { name: "supabase", label: "Supabase", aliases: [] },
  { name: "planetscale", label: "PlanetScale", aliases: [] },

  // ── Cloud platforms ────────────────────────────────────────────────────────
  { name: "aws", label: "AWS", aliases: ["amazon web services", "amazon aws"] },
  {
    name: "gcp",
    label: "Google Cloud",
    aliases: ["google cloud platform", "google cloud", "gcloud"],
  },
  { name: "azure", label: "Microsoft Azure", aliases: ["microsoft azure", "ms azure"] },
  { name: "digitalocean", label: "DigitalOcean", aliases: ["do"] },
  { name: "heroku", label: "Heroku", aliases: [] },
  { name: "vercel", label: "Vercel", aliases: [] },
  { name: "netlify", label: "Netlify", aliases: [] },
  { name: "cloudflare", label: "Cloudflare", aliases: ["cf"] },
  { name: "openshift", label: "OpenShift", aliases: ["red hat openshift"] },
  { name: "ibm-cloud", label: "IBM Cloud", aliases: ["ibm cloud"] },
  { name: "oracle-cloud", label: "Oracle Cloud", aliases: ["oci", "oracle cloud infrastructure"] },
  { name: "alibaba-cloud", label: "Alibaba Cloud", aliases: ["aliyun"] },

  // ── AWS services ───────────────────────────────────────────────────────────
  { name: "aws-lambda", label: "AWS Lambda", aliases: ["lambda", "amazon lambda"] },
  { name: "aws-ec2", label: "Amazon EC2", aliases: ["ec2", "amazon ec2"] },
  { name: "aws-s3", label: "Amazon S3", aliases: ["s3", "amazon s3"] },
  { name: "aws-rds", label: "Amazon RDS", aliases: ["rds", "amazon rds"] },
  { name: "aws-ecs", label: "Amazon ECS", aliases: ["ecs", "amazon ecs"] },
  { name: "aws-eks", label: "Amazon EKS", aliases: ["eks", "amazon eks"] },
  { name: "aws-cloudformation", label: "AWS CloudFormation", aliases: ["cloudformation", "cfn"] },
  { name: "aws-cognito", label: "Amazon Cognito", aliases: ["cognito"] },
  { name: "aws-sqs", label: "Amazon SQS", aliases: ["sqs"] },
  { name: "aws-sns", label: "Amazon SNS", aliases: ["sns"] },
  {
    name: "aws-api-gateway",
    label: "Amazon API Gateway",
    aliases: ["api gateway", "aws api gateway"],
  },
  { name: "aws-cloudwatch", label: "Amazon CloudWatch", aliases: ["cloudwatch"] },
  { name: "aws-iam", label: "AWS IAM", aliases: ["iam", "identity and access management"] },
  { name: "aws-route53", label: "Amazon Route 53", aliases: ["route53", "route 53"] },
  { name: "aws-vpc", label: "Amazon VPC", aliases: ["vpc", "virtual private cloud"] },
  { name: "aws-step-functions", label: "AWS Step Functions", aliases: ["step functions"] },
  { name: "aws-glue", label: "AWS Glue", aliases: ["glue"] },

  // ── GCP services ───────────────────────────────────────────────────────────
  {
    name: "gke",
    label: "Google Kubernetes Engine",
    aliases: ["google kubernetes engine", "gcp gke"],
  },
  {
    name: "gcp-cloud-functions",
    label: "Google Cloud Functions",
    aliases: ["cloud functions", "gcf"],
  },
  {
    name: "gcp-pubsub",
    label: "Google Cloud Pub/Sub",
    aliases: ["pubsub", "pub/sub", "google pubsub"],
  },
  {
    name: "gcp-cloud-storage",
    label: "Google Cloud Storage",
    aliases: ["gcs", "google cloud storage"],
  },
  { name: "gcp-cloud-run", label: "Google Cloud Run", aliases: ["cloud run"] },
  { name: "gcp-firestore", label: "GCP Firestore", aliases: [] },
  { name: "gcp-iam", label: "GCP IAM", aliases: ["google cloud iam"] },
  { name: "gcp-compute", label: "Google Compute Engine", aliases: ["gce", "compute engine"] },

  // ── Azure services ─────────────────────────────────────────────────────────
  { name: "azure-devops", label: "Azure DevOps", aliases: ["ado", "azure devops pipelines"] },
  { name: "azure-functions", label: "Azure Functions", aliases: [] },
  { name: "aks", label: "Azure Kubernetes Service", aliases: ["azure kubernetes service", "aks"] },
  { name: "azure-sql", label: "Azure SQL", aliases: ["azure sql database"] },
  {
    name: "azure-blob",
    label: "Azure Blob Storage",
    aliases: ["azure blob storage", "blob storage"],
  },
  {
    name: "azure-ad",
    label: "Azure Active Directory",
    aliases: ["azure active directory", "entra id", "microsoft entra"],
  },
  {
    name: "azure-arm",
    label: "Azure Resource Manager",
    aliases: ["arm templates", "azure resource manager"],
  },
  { name: "azure-service-bus", label: "Azure Service Bus", aliases: ["service bus"] },
  { name: "azure-cosmos-db", label: "Azure Cosmos DB", aliases: [] },
  { name: "azure-monitor", label: "Azure Monitor", aliases: [] },
  { name: "azure-key-vault", label: "Azure Key Vault", aliases: ["key vault"] },
  { name: "azure-app-service", label: "Azure App Service", aliases: ["app service"] },

  // ── DevOps & infrastructure ────────────────────────────────────────────────
  {
    name: "docker",
    label: "Docker",
    aliases: ["container", "containerisierung", "containerization"],
  },
  {
    name: "kubernetes",
    label: "Kubernetes",
    aliases: ["k8s", "kube", "kubernetes cluster", "container orchestration"],
  },
  { name: "terraform", label: "Terraform", aliases: ["tf", "hashicorp terraform"] },
  { name: "ansible", label: "Ansible", aliases: [] },
  { name: "puppet", label: "Puppet", aliases: [] },
  { name: "chef", label: "Chef", aliases: [] },
  { name: "helm", label: "Helm", aliases: ["helm charts"] },
  { name: "argocd", label: "Argo CD", aliases: ["argo cd", "argocd"] },
  {
    name: "git",
    label: "Git",
    aliases: ["versionskontrolle", "versionsverwaltung", "version control"],
  },
  { name: "github-actions", label: "GitHub Actions", aliases: ["gh actions", "github actions"] },
  { name: "gitlab-ci", label: "GitLab CI", aliases: ["gitlab ci/cd", "gitlab ci"] },
  { name: "jenkins", label: "Jenkins", aliases: [] },
  { name: "circleci", label: "CircleCI", aliases: ["circle ci"] },
  { name: "travis-ci", label: "Travis CI", aliases: ["travis"] },
  { name: "azure-pipelines", label: "Azure Pipelines", aliases: [] },
  { name: "prometheus", label: "Prometheus", aliases: [] },
  { name: "grafana", label: "Grafana", aliases: [] },
  {
    name: "elk-stack",
    label: "ELK Stack",
    aliases: ["elk", "elastic stack", "elasticsearch logstash kibana"],
  },
  { name: "datadog", label: "Datadog", aliases: [] },
  { name: "new-relic", label: "New Relic", aliases: ["newrelic"] },
  { name: "splunk", label: "Splunk", aliases: [] },
  { name: "nginx", label: "NGINX", aliases: [] },
  { name: "apache", label: "Apache HTTP Server", aliases: ["apache", "httpd", "apache httpd"] },
  { name: "caddy", label: "Caddy", aliases: [] },
  { name: "linux", label: "Linux", aliases: ["gnu/linux", "linux administration"] },
  { name: "vagrant", label: "Vagrant", aliases: [] },
  { name: "packer", label: "Packer", aliases: ["hashicorp packer"] },
  { name: "consul", label: "Consul", aliases: ["hashicorp consul"] },
  { name: "vault", label: "HashiCorp Vault", aliases: ["hashicorp vault"] },
  { name: "istio", label: "Istio", aliases: ["service mesh istio"] },
  { name: "linkerd", label: "Linkerd", aliases: [] },
  { name: "pulumi", label: "Pulumi", aliases: [] },
  { name: "fluxcd", label: "Flux CD", aliases: ["flux", "fluxcd", "gitops flux"] },
  { name: "nomad", label: "Nomad", aliases: ["hashicorp nomad"] },
  { name: "envoy", label: "Envoy", aliases: ["envoy proxy"] },

  // ── Messaging & streaming ──────────────────────────────────────────────────
  { name: "kafka", label: "Apache Kafka", aliases: ["apache kafka"] },
  { name: "rabbitmq", label: "RabbitMQ", aliases: [] },
  { name: "activemq", label: "ActiveMQ", aliases: ["apache activemq"] },
  { name: "nats", label: "NATS", aliases: [] },
  { name: "pulsar", label: "Apache Pulsar", aliases: ["pulsar"] },

  // ── Testing ────────────────────────────────────────────────────────────────
  { name: "jest", label: "Jest", aliases: [] },
  { name: "vitest", label: "Vitest", aliases: [] },
  { name: "mocha", label: "Mocha", aliases: [] },
  { name: "chai", label: "Chai", aliases: [] },
  { name: "pytest", label: "pytest", aliases: ["py.test"] },
  { name: "junit", label: "JUnit", aliases: [] },
  { name: "testng", label: "TestNG", aliases: [] },
  { name: "rspec", label: "RSpec", aliases: [] },
  { name: "cucumber", label: "Cucumber", aliases: ["bdd cucumber", "gherkin"] },
  { name: "selenium", label: "Selenium", aliases: ["selenium webdriver"] },
  { name: "cypress", label: "Cypress", aliases: [] },
  { name: "playwright", label: "Playwright", aliases: [] },
  { name: "puppeteer", label: "Puppeteer", aliases: [] },
  { name: "k6", label: "k6", aliases: ["grafana k6", "load testing k6"] },
  { name: "locust", label: "Locust", aliases: [] },
  { name: "postman", label: "Postman", aliases: [] },
  { name: "supertest", label: "Supertest", aliases: [] },
  { name: "testing-library", label: "Testing Library", aliases: ["react testing library", "rtl"] },

  // ── Methodologies & practices ──────────────────────────────────────────────
  {
    name: "agile",
    label: "Agile",
    aliases: ["agile methoden", "agile softwareentwicklung", "agile development"],
  },
  { name: "scrum", label: "Scrum", aliases: ["scrum framework"] },
  { name: "kanban", label: "Kanban", aliases: [] },
  { name: "lean", label: "Lean", aliases: ["lean software development"] },
  { name: "xp", label: "Extreme Programming", aliases: ["extreme programming", "xp"] },
  {
    name: "tdd",
    label: "Test-Driven Development",
    aliases: ["test driven development", "testgetriebene entwicklung"],
  },
  {
    name: "bdd",
    label: "Behavior-Driven Development",
    aliases: ["behavior driven development", "verhaltensgetriebene entwicklung"],
  },
  {
    name: "ddd",
    label: "Domain-Driven Design",
    aliases: ["domain driven design", "domänengetriebenes design"],
  },
  {
    name: "ci-cd",
    label: "CI/CD",
    aliases: [
      "ci cd",
      "continuous integration",
      "continuous delivery",
      "continuous deployment",
      "kontinuierliche integration",
    ],
  },
  { name: "devops", label: "DevOps", aliases: ["dev ops"] },
  {
    name: "sre",
    label: "Site Reliability Engineering",
    aliases: ["site reliability engineering", "site reliability"],
  },
  {
    name: "microservices",
    label: "Microservices",
    aliases: ["microservice architecture", "microservice-architektur"],
  },
  {
    name: "event-driven-architecture",
    label: "Event-Driven Architecture",
    aliases: ["eda", "event driven architecture", "ereignisgesteuerte architektur"],
  },
  { name: "clean-architecture", label: "Clean Architecture", aliases: ["clean code architecture"] },
  {
    name: "pair-programming",
    label: "Pair Programming",
    aliases: ["pair programming", "paarprogrammierung"],
  },
  { name: "code-review", label: "Code Review", aliases: ["code reviews", "codereview"] },
  { name: "serverless", label: "Serverless", aliases: ["serverless computing", "faas"] },
  { name: "gitops", label: "GitOps", aliases: [] },
  {
    name: "platform-engineering",
    label: "Platform Engineering",
    aliases: ["platform engineering", "internal developer platform"],
  },

  // ── Data, ML & AI ──────────────────────────────────────────────────────────
  { name: "pandas", label: "pandas", aliases: [] },
  { name: "numpy", label: "NumPy", aliases: ["numpy"] },
  { name: "scikit-learn", label: "scikit-learn", aliases: ["sklearn", "scikit learn"] },
  { name: "tensorflow", label: "TensorFlow", aliases: ["tf", "tensor flow"] },
  { name: "pytorch", label: "PyTorch", aliases: ["torch"] },
  { name: "keras", label: "Keras", aliases: [] },
  { name: "spark", label: "Apache Spark", aliases: ["apache spark", "pyspark"] },
  { name: "apache-airflow", label: "Apache Airflow", aliases: ["airflow"] },
  { name: "dbt", label: "dbt", aliases: ["data build tool"] },
  { name: "mlflow", label: "MLflow", aliases: [] },
  { name: "kubeflow", label: "Kubeflow", aliases: [] },
  {
    name: "huggingface",
    label: "Hugging Face",
    aliases: ["hugging face", "transformers", "hf transformers"],
  },
  { name: "langchain", label: "LangChain", aliases: [] },
  { name: "openai", label: "OpenAI", aliases: ["openai api", "gpt", "chatgpt api"] },
  { name: "apache-flink", label: "Apache Flink", aliases: ["flink"] },
  { name: "apache-beam", label: "Apache Beam", aliases: ["beam"] },
  { name: "hadoop", label: "Hadoop", aliases: ["apache hadoop", "hdfs"] },
  { name: "databricks", label: "Databricks", aliases: [] },
  { name: "tableau", label: "Tableau", aliases: [] },
  { name: "power-bi", label: "Power BI", aliases: ["powerbi", "microsoft power bi"] },
  { name: "looker", label: "Looker", aliases: ["google looker"] },
  { name: "jupyter", label: "Jupyter", aliases: ["jupyter notebook", "jupyterlab"] },
  { name: "opencv", label: "OpenCV", aliases: [] },
  {
    name: "nlp",
    label: "Natural Language Processing",
    aliases: ["nlp", "natural language processing", "sprachverarbeitung"],
  },
  {
    name: "machine-learning",
    label: "Machine Learning",
    aliases: ["ml", "maschinelles lernen", "ki", "künstliche intelligenz"],
  },
  {
    name: "deep-learning",
    label: "Deep Learning",
    aliases: ["dl", "deep learning", "deep learning neural networks"],
  },
  {
    name: "llm",
    label: "Large Language Models",
    aliases: ["llm", "large language models", "große sprachmodelle"],
  },

  // ── Security ───────────────────────────────────────────────────────────────
  { name: "oauth2", label: "OAuth 2.0", aliases: ["oauth", "oauth 2.0", "oauth2.0"] },
  { name: "jwt", label: "JWT", aliases: ["json web token", "json web tokens"] },
  { name: "saml", label: "SAML", aliases: ["saml 2.0"] },
  { name: "ldap", label: "LDAP", aliases: [] },
  { name: "openssl", label: "OpenSSL", aliases: [] },
  {
    name: "penetration-testing",
    label: "Penetration Testing",
    aliases: ["pentest", "pen testing", "penetrationstest"],
  },
  { name: "owasp", label: "OWASP", aliases: [] },
  { name: "gdpr", label: "GDPR", aliases: ["dsgvo", "general data protection regulation"] },
  { name: "soc2", label: "SOC 2", aliases: ["soc 2", "soc2 compliance"] },
  {
    name: "iso27001",
    label: "ISO 27001",
    aliases: ["iso 27001", "information security management"],
  },
  {
    name: "zero-trust",
    label: "Zero Trust",
    aliases: ["zero trust security", "zero trust architecture"],
  },
  { name: "keycloak", label: "Keycloak", aliases: [] },

  // ── Tools & build ──────────────────────────────────────────────────────────
  { name: "figma", label: "Figma", aliases: [] },
  { name: "jira", label: "Jira", aliases: ["atlassian jira"] },
  { name: "confluence", label: "Confluence", aliases: ["atlassian confluence"] },
  { name: "slack", label: "Slack", aliases: [] },
  { name: "notion", label: "Notion", aliases: [] },
  {
    name: "vscode",
    label: "Visual Studio Code",
    aliases: ["visual studio code", "vs code", "code editor"],
  },
  { name: "intellij-idea", label: "IntelliJ IDEA", aliases: ["intellij", "idea"] },
  { name: "vim", label: "Vim", aliases: ["vi", "neovim"] },
  { name: "npm", label: "npm", aliases: ["node package manager"] },
  { name: "yarn", label: "Yarn", aliases: ["yarn berry", "yarn classic"] },
  { name: "pnpm", label: "pnpm", aliases: [] },
  { name: "maven", label: "Maven", aliases: ["apache maven"] },
  { name: "gradle", label: "Gradle", aliases: [] },
  { name: "cmake", label: "CMake", aliases: [] },
  { name: "make", label: "Make", aliases: ["gnu make"] },
  { name: "bazel", label: "Bazel", aliases: [] },
  { name: "nx", label: "Nx", aliases: ["nrwl nx"] },
  { name: "turborepo", label: "Turborepo", aliases: ["turbo repo", "turbo"] },
  { name: "lerna", label: "Lerna", aliases: [] },
  { name: "sonarqube", label: "SonarQube", aliases: ["sonar", "sonarqube"] },
  { name: "sentry", label: "Sentry", aliases: [] },
];

/** Upsert canonical skills by name; updates label and aliases on conflict. */
export async function seedSkills(db: Database): Promise<void> {
  if (SKILL_SEED_ENTRIES.length === 0) {
    return;
  }

  await db
    .insert(skills)
    .values(SKILL_SEED_ENTRIES)
    .onConflictDoUpdate({
      target: skills.name,
      set: {
        label: sql`excluded.label`,
        aliases: sql`excluded.aliases`,
      },
    });
}
